print( a        b           pow(a , b)  )
print( 1	2	    1           )
print( 2        3           8           )
print( 2        4	    81          )
print( 4        5           1024        )
print( 5        6           15625       )