<<<<<<< HEAD
num1 = int(input("enter first number:"))
num2 = int(input("enter second number:"))
num3 = int(input("enter third number:"))
num4 = int(input("enter fourth number:"))
num5 = int(input("enter fifth number:"))
num6 = int(input(" enter sixth number:"))
num7 = int(input(" enter seventh number:"))
num8 = int(input("enter eigth number:"))
num9 = int(input("enter ninth number:"))
num10 = int(input("enter tenth number:"))
sum = (num1 + num2 + num3 + num4 + num5 +  num6 + num7 + num8 + num9 + num10)
=======
num1 = int(input("enter first number:"))
num2 = int(input("enter second number:"))
num3 = int(input("enter third number:"))
num4 = int(input("enter fourth number:"))
num5 = int(input("enter fifth number:"))
num6 = int(input(" enter sixth number:"))
num7 = int(input(" enter seventh number:"))
num8 = int(input("enter eigth number:"))
num9 = int(input("enter ninth number:"))
num10 = int(input("enter tenth number:"))
sum = (num1 + num2 + num3 + num4 + num5 +  num6 + num7 + num8 + num9 + num10)
>>>>>>> 878da3792fa3f45869d527fb1cbb6b45ac1f8a10
print(sum)