spring.application.name=Full-Ecommerce-App
# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/E-Commerece-App

spring.config.import=Secret.properties

# JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect